#!/usr/bin/env bash

progname=$(basename $0)
svnsync_option="--non-interactive"

usage() {
    echo "Usage: $progname [OPTION]... ROOT"
}

help() {
    echo "Subversion mirror synchronizer"
    echo ""
    usage
    echo ""
    echo "Options:"
    echo "  -h, --help          display this help and exit"
    echo "  --username          connect to the source repository with username ARG"
    echo "  --password          connect to the source repository with password ARG"
}

pattern=".*|_*"
args=$(getopt -o h --long help,username:,password: -n$progname -- $@)
[ $? -eq 0 ] || exit 0

eval set -- $args
while true; do
    case "$1" in
        -h|--help) shift; help; exit 0;;
        --username) svnsync_option="$svnsync_option --source-username=$2"; shift 2;;
        --password) svnsync_option="$svnsync_option --source-password=$2"; shift 2;;
        --) shift; break;;
    esac
done

root=$1

if [ -z "$root" ]; then
    usage >&2
    exit 1
fi


if ! [ -d "$root" ]; then
    echo "no such directory: $root" >&2
    exit 1
fi

repositories=$(find "$root" -mindepth 1 -maxdepth 1 -type d -not \( -name ".*" -o -name "_*" \) )
for repo in $repositories; do
    echo "Synchronizing $repo"
    svnsync sync "file://$(realpath $repo)" $svnsync_option
done
